---
name: Workflow Release Service

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        options:
          - dev
          - prd
      helm_chart_cosmo_version:
        type: string
        default: ""
      otellcollector_version:
        type: string
        default: ""
      graphqlmetrics_version:
        type: string
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.event.repository.name }}-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p gitops/${{ inputs.stage }}

          echo "${{ inputs.helm_chart_cosmo_version }}" >> gitops/${{ inputs.stage }}/helm_chart_cosmo_version
          echo "${{ inputs.otellcollector_version }}" >> gitops/${{ inputs.stage }}/otellcollector_version
          echo "${{ inputs.graphqlmetrics_version }}" >> gitops/${{ inputs.stage }}/graphqlmetrics_version

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update gitops/${{ inputs.stage }}/*"
          skip_fetch: true
          skip_checkout: true
          file_pattern: "gitops/${{ inputs.stage }}/*"
